baseurl: /newhaven
permalink: pretty
markdown: kramdown
paginate: 5
repo: newhaven
github_org: maptime
maptime:
  chapter: maptime New Haven
  twitter: maptimeNewHaven
  #disqus: YOUR DISQUS USERNAME
